"""Add DPDP consent given and timestamp columns to problem model

Revision ID: 573e0e40e1ed
Revises: 1c3269c107b8
Create Date: 2026-08-23 09:55:42.042582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573e0e40e1ed'
down_revision: Union[str, Sequence[str], None] = '1c3269c107b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dpdp_consent_given', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dpdp_consent_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('dpdp_consent_timestamp')
        batch_op.drop_column('dpdp_consent_given')

    # ### end Alembic commands ###
