"""Add needs_human_review and ai_confidence columns to problem model

Revision ID: 6a5d0ef4b82b
Revises: 7469d4027d2b
Create Date: 2026-08-23 09:35:37.577820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5d0ef4b82b'
down_revision: Union[str, Sequence[str], None] = '7469d4027d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('needs_human_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('needs_human_review')
        batch_op.drop_column('ai_confidence')

    # ### end Alembic commands ###
