"""Add query performance indexes on problem category status university district

Revision ID: e0fe72a8de61
Revises: 573e0e40e1ed
Create Date: 2026-08-23 10:22:32.011698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fe72a8de61'
down_revision: Union[str, Sequence[str], None] = '573e0e40e1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_ai_predicted_category'), ['ai_predicted_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_assigned_university'), ['assigned_university'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_district'), ['district'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_status'))
        batch_op.drop_index(batch_op.f('ix_problems_district'))
        batch_op.drop_index(batch_op.f('ix_problems_assigned_university'))
        batch_op.drop_index(batch_op.f('ix_problems_ai_predicted_category'))

    # ### end Alembic commands ###
